# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15d8913052bce0cb05212f463f0fbc49378018baa76e4c8f1ce73192d67653f9043703c41bcd8d1eee324559e9aecb8fa1feef6f6bfdc0c6aed97e20e079a80e

test:
  secret_key_base: 1880ebdc7244d7cad18ed8ec0f4970d0f1ed32baf3cfe8977aca7c63057d2d44dcb82bdd426cdb3b6d126a0b8e760ebc7f0e2089b5bf2fee20548e7bff2c91d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
